name: Atualizar Paineis do Power BI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar o Power BI CLI
      run: |
        sudo npm install -g powerbi-cli

    - name: Exportar painéis do Power BI
      run: |
        pbi report export --workspace 172a9150-5bfa-48df-9916-7929247d8725 --outputPath ./reports

    - name: Adicionar, confirmar e enviar atualizações para o GitHub
      run: |
        git config --global user.email "samuel.massucci@gruppytecnologia.onmicrosoft.com"
        git config --global user.name "Samuel Massucci"
        git add .
        git commit -m "Atualizando painéis do Power BI"
        git push
